import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    brandTagline: 'your calm money space',
    account: 'My account',
    personalFinances: 'Personal finances',
    workspace: 'Workspace',
    overview: 'Overview',
    transactions: 'Transactions',
    budgets: 'Budgets',
    savingsGoals: 'Savings goals',
    recurring: 'Recurring',
    categories: 'Categories',
    accountSettings: 'Account settings',
    logout: 'Log out',
    login: 'Login',
    createAccount: 'Create account',
    menu: 'Menu',
    close: 'Close',
    smallSteps: 'Small steps, clearer choices.',
    personalSpace: 'Personal space',
    keepDetails: 'Keep your details and security up to date.',
    personalDetails: 'Personal details',
    changePassword: 'Change password',
    username: 'Username',
    email: 'Email',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    saveDetails: 'Save details',
    saving: 'Saving...',
    updatePassword: 'Change password',
    updating: 'Updating...',
    profileUpdated: 'Account details updated.',
    passwordUpdated: 'Password changed successfully.',
    passwordsMismatch: 'The new passwords do not match.',
    loadingAccount: 'Loading account...',
    language: 'Language',
    finance: 'Finance',
    setup: 'Setup',
    planning: 'Planning',
    automation: 'Automation',
    month: 'Month',
    category: 'Category',
    type: 'Type',
    allCategories: 'All categories',
    allTypes: 'All types',
    clearFilters: 'Clear filters',
    income: 'Income',
    expense: 'Expense',
    addTransaction: 'Add transaction',
    editTransaction: 'Edit transaction',
    saveTransaction: 'Save transaction',
    updateTransaction: 'Update transaction',
    cancel: 'Cancel',
    description: 'Description',
    amount: 'Amount',
    date: 'Date',
    recentTransactions: 'Recent transactions',
    noTransactions: 'No transactions yet.',
    filterTransactions: 'Filter transactions',
    createCategory: 'Create category',
    editCategory: 'Edit category',
    saveCategory: 'Save category',
    updateCategory: 'Update category',
    allCategoriesTitle: 'All categories',
    noCategories: 'No categories yet.',
    loading: 'Loading...',
    dashboard: 'Budget dashboard',
    totalIncome: 'Total income',
    totalExpenses: 'Total expenses',
    balance: 'Balance',
    byCategory: 'By category',
    noData: 'No data yet.',
    monthlyBudgets: 'Monthly budgets',
    setBudget: 'Set a budget',
    editBudget: 'Edit budget',
    limit: 'Limit',
    saveBudget: 'Save budget',
    updateBudget: 'Update budget',
    noBudgets: 'No budgets set for this month.',
    budgetExceeded: 'Budget exceeded',
    budgetUsed: '80% of budget used',
    savingsPlanning: 'Savings goals',
    createGoal: 'Create goal',
    editGoal: 'Edit goal',
    targetAmount: 'Target amount',
    alreadySaved: 'Already saved',
    deadline: 'Deadline',
    saveGoal: 'Save goal',
    updateGoal: 'Update goal',
    noGoals: 'No savings goals yet.',
    goalCompleted: 'Goal completed',
    recurringTransactions: 'Recurring transactions',
    createRecurring: 'Create recurring transaction',
    editRecurring: 'Edit recurring transaction',
    nextDate: 'Next date',
    save: 'Save',
    update: 'Update',
    noRecurring: 'No recurring transactions yet.',
    generateNow: 'Generate now',
  },
  pt: {
    brandTagline: 'o teu espaço financeiro',
    account: 'A minha conta',
    personalFinances: 'Finanças pessoais',
    workspace: 'Área de trabalho',
    overview: 'Visão geral',
    transactions: 'Transações',
    budgets: 'Orçamentos',
    savingsGoals: 'Objetivos de poupança',
    recurring: 'Recorrentes',
    categories: 'Categorias',
    accountSettings: 'Definições da conta',
    logout: 'Terminar sessão',
    login: 'Entrar',
    createAccount: 'Criar conta',
    menu: 'Menu',
    close: 'Fechar',
    smallSteps: 'Pequenos passos, escolhas mais claras.',
    personalSpace: 'Espaço pessoal',
    keepDetails: 'Mantém os teus dados e segurança atualizados.',
    personalDetails: 'Dados pessoais',
    changePassword: 'Alterar palavra-passe',
    username: 'Nome de utilizador',
    email: 'Email',
    currentPassword: 'Palavra-passe atual',
    newPassword: 'Nova palavra-passe',
    confirmPassword: 'Confirmar palavra-passe',
    saveDetails: 'Guardar dados',
    saving: 'A guardar...',
    updatePassword: 'Alterar palavra-passe',
    updating: 'A atualizar...',
    profileUpdated: 'Dados da conta atualizados.',
    passwordUpdated: 'Palavra-passe alterada com sucesso.',
    passwordsMismatch: 'As novas palavras-passe não coincidem.',
    loadingAccount: 'A carregar conta...',
    language: 'Idioma',
    finance: 'Finanças',
    setup: 'Configuração',
    planning: 'Planeamento',
    automation: 'Automação',
    month: 'Mês',
    category: 'Categoria',
    type: 'Tipo',
    allCategories: 'Todas as categorias',
    allTypes: 'Todos os tipos',
    clearFilters: 'Limpar filtros',
    income: 'Receita',
    expense: 'Despesa',
    addTransaction: 'Adicionar transação',
    editTransaction: 'Editar transação',
    saveTransaction: 'Guardar transação',
    updateTransaction: 'Atualizar transação',
    cancel: 'Cancelar',
    description: 'Descrição',
    amount: 'Valor',
    date: 'Data',
    recentTransactions: 'Transações recentes',
    noTransactions: 'Ainda não existem transações.',
    filterTransactions: 'Filtrar transações',
    createCategory: 'Criar categoria',
    editCategory: 'Editar categoria',
    saveCategory: 'Guardar categoria',
    updateCategory: 'Atualizar categoria',
    allCategoriesTitle: 'Todas as categorias',
    noCategories: 'Ainda não existem categorias.',
    loading: 'A carregar...',
    dashboard: 'Dashboard financeiro',
    totalIncome: 'Total de receitas',
    totalExpenses: 'Total de despesas',
    balance: 'Saldo',
    byCategory: 'Por categoria',
    noData: 'Ainda não existem dados.',
    monthlyBudgets: 'Orçamentos mensais',
    setBudget: 'Definir orçamento',
    editBudget: 'Editar orçamento',
    limit: 'Limite',
    saveBudget: 'Guardar orçamento',
    updateBudget: 'Atualizar orçamento',
    noBudgets: 'Ainda não existem orçamentos para este mês.',
    budgetExceeded: 'Orçamento ultrapassado',
    budgetUsed: '80% do orçamento utilizado',
    savingsPlanning: 'Objetivos de poupança',
    createGoal: 'Criar objetivo',
    editGoal: 'Editar objetivo',
    targetAmount: 'Valor alvo',
    alreadySaved: 'Valor já poupado',
    deadline: 'Prazo',
    saveGoal: 'Guardar objetivo',
    updateGoal: 'Atualizar objetivo',
    noGoals: 'Ainda não existem objetivos de poupança.',
    goalCompleted: 'Objetivo concluído',
    recurringTransactions: 'Transações recorrentes',
    createRecurring: 'Criar transação recorrente',
    editRecurring: 'Editar transação recorrente',
    nextDate: 'Próxima data',
    save: 'Guardar',
    update: 'Atualizar',
    noRecurring: 'Ainda não existem transações recorrentes.',
    generateNow: 'Gerar agora',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'pt');

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key) => translations[language][key] || translations.en[key] || key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside a LanguageProvider');
  return context;
};
